# Generated by Django 2.2 on 2021-01-31 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210131_0835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costumer',
            old_name='name',
            new_name='Cname',
        ),
    ]
