# Generated by Django 2.2 on 2021-01-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_pr_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='PA_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='buyer',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='PA_type',
            field=models.CharField(default='credit', max_length=32),
        ),
    ]
