# Generated by Django 2.2 on 2021-01-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210131_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='PA_type',
            field=models.CharField(default=0, max_length=32),
        ),
        migrations.AlterField(
            model_name='payment',
            name='buyer',
            field=models.CharField(default=0, max_length=32),
        ),
    ]
